### ISSUE TITLE
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. 

### ISSUE THREAD

**Issue by KTsarlz** [terryx/atom-web-syntax#1]
I'm having deprecated error on atom 1.13

**Comment by terryx** [comment]
This is fixed in v0.9.8

**Comment by PavelTT** [comment]
Hello!
Sorry, I could be wrong...
This app was written by You?
https://apps.getpebble.com/en_US/application/56231c63ade802b29d00002b?section=watchapps
